DROP TABLE IF EXISTS student, professor, course, students_on_the_course, student_point_course, professor_on_the_course, courses_taken CASCADE;



CREATE TABLE IF NOT EXISTS student
(
    student_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               varchar(255),
    address            varchar(255),
    tel                varchar(255),
    email              varchar(255),
    record_book_number INTEGER,
    avg_point          float
);

CREATE TABLE IF NOT EXISTS professor
(
    professor_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(255),
    address      varchar(255),
    tel          varchar(255),
    payment      FLOAT
);

CREATE TABLE IF NOT EXISTS course
(
    course_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      varchar(255),
    number    INTEGER,
    price     FLOAT

);

CREATE TABLE IF NOT EXISTS students_on_the_course
(
    student_id bigint references student (student_id) on delete cascade,
    course_id  bigint references course (course_id) on delete cascade
);

CREATE TABLE IF NOT EXISTS student_point_course
(
    student_id bigint references student (student_id) on delete cascade,
    course_id  bigint references course (course_id) on delete cascade,
    point      integer
);

CREATE TABLE IF NOT EXISTS professor_on_the_course
(
    professor_id bigint,
    course_id  bigint
);

CREATE TABLE IF NOT EXISTS courses_taken
(
    student_id bigint,
    course_id  bigint
);
