# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  coursemodel-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=courseModel
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 127.0.0.1:5431:5432
